global:
    kolla:
        all:
            kubernetes_entrypoint: true
        glance:
            create_db:
                job:
                    dependencies:
                        SERVICE:
                        - mariadb
            manage_db:
                job:
                    ceph_backend: true
                    dependencies:
                        SERVICE:
                        - mariadb
                        JOBS:
                        - glance-create-db
            create_keystone_user:
                job:
                    dependencies:
                        JOBS:
                        - glance-create-keystone-service
                        SERVICE:
                        - keystone-admin
            create_keystone_service:
                job:
                    dependencies:
                        SERVICE:
                        - keystone-admin
            create_keystone_endpoint:
                public:
                    job:
                        dependencies:
                            JOBS:
                            - glance-create-keystone-service
                            - glance-create-keystone-user
                            - glance-create-keystone-endpoint-internal
                            - glance-create-keystone-endpoint-admin
                            SERVICE:
                            - keystone-admin
                internal:
                    job:
                        dependencies:
                            JOBS:
                            - glance-create-keystone-service
                            - glance-create-keystone-user
                            - glance-create-keystone-endpoint-admin
                            SERVICE:
                            - keystone-admin
                admin:
                    job:
                        dependencies:
                            JOBS:
                            - glance-create-keystone-service
                            - glance-create-keystone-user
                            SERVICE:
                            - keystone-admin
            api:
                all:
                    ceph_backend: true
                deployment:
                    dependencies:
                        JOBS:
                        - glance-create-keystone-endpoint-public
                        - glance-create-keystone-endpoint-internal
                        - glance-create-keystone-endpoint-admin
                        - glance-create-db
                        - glance-manage-db
                        SERVICE:
                        - mariadb
                        - keystone-admin
                svc:
                    port_external: true

            registry:
                deployment:
                    dependencies:
                        JOBS:
                        - glance-create-keystone-endpoint-public
                        - glance-create-keystone-endpoint-internal
                        - glance-create-keystone-endpoint-admin
                        - glance-create-db
                        - glance-manage-db
                        SERVICE:
                        - mariadb
                        - keystone-admin
