global:
    kolla:
        all:
            kubernetes_entrypoint: true
        memcached:
            deployment:
                dependencies:
                    service:
                    - memcached

