global:
    kolla:
        all:
            kubernetes_entrypoint: true
        horizon:
            deployment:
                dependencies:
                    service:
                    - horizon
                    - keystone-internal

