global:
    kolla:
        all:
            kubernetes_entrypoint: true
        nova:
            all:
                ceph_backend: true
            compute:
                daemonset:
                    dependencies:
                        service:
                        - nova-metadata
                        - nova-api
                        socket:
                        - /var/run/libvirt/libvirt-sock
            libvirt:
                daemonset:
                    dependencies:
                        service:
                        - nova-metadata
                        - nova-api
